name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  guacamole_server:
    name: Build guacamole-server
    runs-on: ubuntu-latest
    steps:
          # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Copy Dockerfile  # 拷贝Dockerfile到发布目录 ##生成随机数 echo "$RANDOM"|md5sum|cut -c 5-15
        run: mv Dockerfile-linuxserver Dockerfile
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/guacd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/guacd:1.4.0
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacd:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/guacd:cache,mode=max
